title: "My Professional Portfolio"
description: "Showcasing my work and projects"
baseurl: "" # Để trống nếu không dùng subdirectory
markdown_ext: "markdown,md"
permalink: /:basename/
url: "https://namcreative.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Navigation
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

author:
  name: "Nam"
  email: "namvuhoai.forwork@gmail.com"
  avatar: "/assets/images/avatar.jpg"
  bio: "A passionate developer and designer"
  links:
    - label: "GitHub"
      url: "https://github.com/namcreative"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/namvuhoai"
